### ISSUE TITLE
ModuleNotFoundError: No module named 'exceptions'

### ISSUE THREAD

**Issue by My12123** [alicewish/MomoTranslator#11]
![2023-04-25_13-24-48](https://user-images.githubusercontent.com/49092250/234250258-5177afd4-3ea5-4471-a65b-f0a6edde5073.png)
```python
(venv) F:\MomoTranslator>python pyqt5_momotranslator.py
Traceback (most recent call last):
  File "F:\MomoTranslator\pyqt5_momotranslator.py", line 48, in <module>
    from docx import Document
  File "F:\MomoTranslator\venv\lib\site-packages\docx.py", line 30, in <module>
    from exceptions import PendingDeprecationWarning
ModuleNotFoundError: No module named 'exceptions'
``` 
![2023-04-25_13-30-48](https://user-images.githubusercontent.com/49092250/234250615-ef4efe33-3ff7-402d-9cad-14c10d377990.png)

**Comment by alicewish** [comment]
这应该是虚拟环境下pip安装包没装完整造成的。
