### ISSUE TITLE
OSError: cannot open resource、好像是字体文件的问题，请问怎么解决呢。

### ISSUE THREAD

**Issue by jaclla** [alicewish/MomoTranslator#21]
m1 mac上运行的
![image](https://github.com/alicewish/MomoTranslator/assets/34511671/6d004ae8-e94c-4810-b152-509ec94f68d4)

**Comment by jaclla** [comment]
我看 lol 之前回复过说把字体放在指定的目录位置，请问字体文件是哪些，放在哪个位置？

**Comment by alicewish** [comment]
不要用虚拟环境，配系统环境重试

**Comment by jaclla** [comment]
你好我是陈龙，我已经收到了你发的邮件。

**Comment by jaclla** [comment]
我好像没用使用虚拟环境

**Comment by alicewish** [comment]
不用pyenv用系统python解释器然后再给下报错

**Comment by alicewish** [comment]
环境改成3.10吧，没在3.11下测试

**Comment by jaclla** [comment]
![image](https://github.com/alicewish/MomoTranslator/assets/34511671/588d24c5-e838-472a-93d0-67383ff7362e)
还是不行

**Comment by jaclla** [comment]
一个一个模块安装的。。。直接运行python3 pyqt5_momotranslator.py一堆确实模块

**Comment by alicewish** [comment]
更新最新代码然后重新给出报错信息

**Comment by jaclla** [comment]
这是最新的代码执行后的报错：
![image](https://github.com/alicewish/MomoTranslator/assets/34511671/b68ef14b-0fbb-43ea-8b2a-b943ebf73487)

**Comment by KITResonance** [comment]
![image](https://github.com/alicewish/MomoTranslator/assets/80582018/89294520-f442-4250-b900-b7d31e72da8b)
从C:\Windows\Fronts随便找个顺眼的字体替换上就行，不过我是win环境，仅供你参考

**Comment by jaclla** [comment]
> ![image](https://user-images.githubusercontent.com/80582018/276866501-89294520-f442-4250-b900-b7d31e72da8b.png) 从C:\Windows\Fronts随便找个顺眼的字体替换上就行，不过我是win环境，仅供你参考

可行！按照报错在/Users/logic/Documents/默墨汉化/FontLibrary/msyh.ttc 创建了字体文件重新启动就好了，页面目前出来了！3q

**Comment by jaclla** [comment]
运行的时候报错。


xd2023-10-20 17:03:16.881 | DEBUG    | __main__:istart_task:4817 - [0]分析画格 - /Users/logic/Downloads/#R-15 ファイナルワンの追葬 - 泉美＠よんそくほこう的插画 - pixiv
2023-10-20 17:03:16.882 | WARNING  | __main__:analyze1frame:5071 - img_file=PosixPath('/Users/logic/Downloads/#R-15 ファイナルワンの追葬 - 泉美＠よんそくほこう的插画 - pixiv/65393908_p2.png')
2023-10-20 17:03:17.049 | INFO     | __main__:analyze1frame:5104 - 65393908_p2边框颜色中出现次数最多的颜色：[255 255 255 255], 颜色名称：white, color_ratio0=0.3505
[1]filter_cnt.br=(640, 2829, 57, 53),filter_cnt.area=1062,filter_cnt.perimeter=168.55
[2]filter_cnt.br=(935, 2528, 145, 362),filter_cnt.area=28721,filter_cnt.perimeter=1054.78
[3]filter_cnt.br=(737, 2528, 273, 250),filter_cnt.area=46380,filter_cnt.perimeter=3322.67
[4]filter_cnt.br=(507, 2528, 281, 362),filter_cnt.area=78894,filter_cnt.perimeter=1632.42
[5]filter_cnt.br=(259, 2528, 243, 362),filter_cnt.area=55924,filter_cnt.perimeter=1200.22
[6]filter_cnt.br=(29, 2528, 313, 249),filter_cnt.area=54126,filter_cnt.perimeter=4637.96
[7]filter_cnt.br=(38, 2268, 214, 231),filter_cnt.area=33769,filter_cnt.perimeter=908.06
[8]filter_cnt.br=(404, 2198, 129, 86),filter_cnt.area=4862,filter_cnt.perimeter=884.65
[9]filter_cnt.br=(767, 2188, 130, 213),filter_cnt.area=19662,filter_cnt.perimeter=560.16
[10]filter_cnt.br=(153, 2180, 58, 92),filter_cnt.area=3976,filter_cnt.perimeter=248.21
[11]filter_cnt.br=(876, 2132, 51, 75),filter_cnt.area=2880,filter_cnt.perimeter=206.41
[12]filter_cnt.br=(377, 2095, 172, 184),filter_cnt.area=14534,filter_cnt.perimeter=1735.16
[13]filter_cnt.br=(293, 1984, 106, 59),filter_cnt.area=4898,filter_cnt.perimeter=387.58
[14]filter_cnt.br=(31, 1683, 121, 122),filter_cnt.area=11150,filter_cnt.perimeter=397.06
[15]filter_cnt.br=(398, 1661, 174, 240),filter_cnt.area=28437,filter_cnt.perimeter=679.90
[16]filter_cnt.br=(707, 1647, 119, 131),filter_cnt.area=10072,filter_cnt.perimeter=1375.64
[17]filter_cnt.br=(653, 1566, 91, 167),filter_cnt.area=3554,filter_cnt.perimeter=655.97
[18]filter_cnt.br=(914, 1489, 124, 249),filter_cnt.area=21502,filter_cnt.perimeter=621.33
[19]filter_cnt.br=(927, 1468, 153, 119),filter_cnt.area=4591,filter_cnt.perimeter=597.02
[20]filter_cnt.br=(789, 1450, 291, 593),filter_cnt.area=57996,filter_cnt.perimeter=3714.43
[21]filter_cnt.br=(653, 1450, 156, 165),filter_cnt.area=17588,filter_cnt.perimeter=1881.21
[22]filter_cnt.br=(344, 1450, 204, 275),filter_cnt.area=31134,filter_cnt.perimeter=1564.40
[23]filter_cnt.br=(81, 1450, 305, 304),filter_cnt.area=51380,filter_cnt.perimeter=4923.96
[24]filter_cnt.br=(74, 974, 203, 214),filter_cnt.area=29720,filter_cnt.perimeter=677.60
[25]filter_cnt.br=(314, 951, 102, 168),filter_cnt.area=12424,filter_cnt.perimeter=495.39
[26]filter_cnt.br=(572, 933, 96, 194),filter_cnt.area=11542,filter_cnt.perimeter=508.11
[27]filter_cnt.br=(446, 1064, 121, 218),filter_cnt.area=18286,filter_cnt.perimeter=555.67
[28]filter_cnt.br=(0, 902, 139, 543),filter_cnt.area=36924,filter_cnt.perimeter=4158.04
[29]filter_cnt.br=(321, 716, 93, 89),filter_cnt.area=7202,filter_cnt.perimeter=348.85
[30]filter_cnt.br=(24, 568, 122, 177),filter_cnt.area=16930,filter_cnt.perimeter=500.86
[31]filter_cnt.br=(468, 440, 156, 202),filter_cnt.area=25174,filter_cnt.perimeter=603.87
[32]filter_cnt.br=(630, 438, 275, 341),filter_cnt.area=59196,filter_cnt.perimeter=1269.28
[33]filter_cnt.br=(142, 342, 99, 272),filter_cnt.area=18170,filter_cnt.perimeter=711.37
[34]filter_cnt.br=(896, 340, 153, 157),filter_cnt.area=17770,filter_cnt.perimeter=540.80
[35]filter_cnt.br=(714, 327, 95, 97),filter_cnt.area=5531,filter_cnt.perimeter=524.70
[36]filter_cnt.br=(0, 289, 196, 587),filter_cnt.area=66292,filter_cnt.perimeter=1987.36
[37]filter_cnt.br=(688, 267, 123, 112),filter_cnt.area=6662,filter_cnt.perimeter=1314.51
[38]filter_cnt.br=(272, 199, 68, 80),filter_cnt.area=1968,filter_cnt.perimeter=315.36
[39]filter_cnt.br=(901, 72, 128, 239),filter_cnt.area=20427,filter_cnt.perimeter=688.24
[40]filter_cnt.br=(421, 35, 183, 269),filter_cnt.area=27778,filter_cnt.perimeter=841.13
[41]filter_cnt.br=(117, 0, 260, 220),filter_cnt.area=41694,filter_cnt.perimeter=2905.20
[1]filter_cnt.br=(935, 2528, 145, 362),filter_cnt.area=28710,filter_cnt.perimeter=1053.03
[2]filter_cnt.br=(737, 2528, 273, 250),filter_cnt.area=46216,filter_cnt.perimeter=3292.67
[3]filter_cnt.br=(507, 2528, 281, 362),filter_cnt.area=78852,filter_cnt.perimeter=1633.01
[4]filter_cnt.br=(259, 2528, 243, 362),filter_cnt.area=55902,filter_cnt.perimeter=1200.22
[5]filter_cnt.br=(29, 2528, 313, 249),filter_cnt.area=53720,filter_cnt.perimeter=4793.08
[6]filter_cnt.br=(38, 2268, 214, 231),filter_cnt.area=33747,filter_cnt.perimeter=908.06
[7]filter_cnt.br=(406, 2198, 127, 86),filter_cnt.area=4812,filter_cnt.perimeter=871.09
[8]filter_cnt.br=(767, 2188, 130, 213),filter_cnt.area=19652,filter_cnt.perimeter=560.74
[9]filter_cnt.br=(153, 2180, 58, 92),filter_cnt.area=3974,filter_cnt.perimeter=248.21
[10]filter_cnt.br=(876, 2132, 51, 75),filter_cnt.area=2872,filter_cnt.perimeter=206.41
[11]filter_cnt.br=(377, 2096, 172, 182),filter_cnt.area=14028,filter_cnt.perimeter=1971.38
[12]filter_cnt.br=(293, 1984, 106, 59),filter_cnt.area=4875,filter_cnt.perimeter=389.34
[13]filter_cnt.br=(31, 1683, 121, 122),filter_cnt.area=11140,filter_cnt.perimeter=397.06
[14]filter_cnt.br=(398, 1661, 174, 240),filter_cnt.area=28418,filter_cnt.perimeter=679.31
[15]filter_cnt.br=(707, 1648, 119, 130),filter_cnt.area=10006,filter_cnt.perimeter=1380.82
[16]filter_cnt.br=(653, 1566, 91, 167),filter_cnt.area=3532,filter_cnt.perimeter=656.56
[17]filter_cnt.br=(914, 1489, 124, 249),filter_cnt.area=21486,filter_cnt.perimeter=620.74
[18]filter_cnt.br=(927, 1468, 153, 119),filter_cnt.area=4575,filter_cnt.perimeter=596.19
[19]filter_cnt.br=(789, 1450, 291, 593),filter_cnt.area=55642,filter_cnt.perimeter=4513.22
[20]filter_cnt.br=(685, 1450, 124, 160),filter_cnt.area=14490,filter_cnt.perimeter=1426.38
[21]filter_cnt.br=(344, 1450, 204, 275),filter_cnt.area=31040,filter_cnt.perimeter=1575.71
[22]filter_cnt.br=(82, 1450, 303, 304),filter_cnt.area=50194,filter_cnt.perimeter=5511.45
[23]filter_cnt.br=(446, 1064, 121, 218),filter_cnt.area=18234,filter_cnt.perimeter=555.09
[24]filter_cnt.br=(74, 974, 203, 214),filter_cnt.area=29671,filter_cnt.perimeter=678.18
[25]filter_cnt.br=(314, 951, 102, 168),filter_cnt.area=12394,filter_cnt.perimeter=492.80
[26]filter_cnt.br=(572, 933, 96, 194),filter_cnt.area=11503,filter_cnt.perimeter=506.70
[27]filter_cnt.br=(131, 904, 501, 541),filter_cnt.area=150206,filter_cnt.perimeter=9982.77
[28]filter_cnt.br=(0, 902, 139, 543),filter_cnt.area=34298,filter_cnt.perimeter=4566.34
[29]filter_cnt.br=(321, 716, 93, 89),filter_cnt.area=7178,filter_cnt.perimeter=350.02
[30]filter_cnt.br=(24, 568, 122, 177),filter_cnt.area=16904,filter_cnt.perimeter=500.86
[31]filter_cnt.br=(468, 440, 156, 202),filter_cnt.area=25132,filter_cnt.perimeter=603.29
[32]filter_cnt.br=(630, 438, 275, 341),filter_cnt.area=59164,filter_cnt.perimeter=1264.45
[33]filter_cnt.br=(142, 342, 99, 272),filter_cnt.area=18124,filter_cnt.perimeter=711.37
[34]filter_cnt.br=(896, 340, 153, 157),filter_cnt.area=17742,filter_cnt.perimeter=539.63
[35]filter_cnt.br=(714, 327, 95, 97),filter_cnt.area=5516,filter_cnt.perimeter=523.29
[36]filter_cnt.br=(0, 289, 196, 587),filter_cnt.area=66228,filter_cnt.perimeter=1988.19
[37]filter_cnt.br=(688, 267, 123, 112),filter_cnt.area=6576,filter_cnt.perimeter=1346.07
[38]filter_cnt.br=(273, 199, 67, 80),filter_cnt.area=1952,filter_cnt.perimeter=315.36
[39]filter_cnt.br=(902, 72, 127, 239),filter_cnt.area=20374,filter_cnt.perimeter=686.83
[40]filter_cnt.br=(421, 35, 182, 269),filter_cnt.area=27714,filter_cnt.perimeter=840.65
[41]filter_cnt.br=(117, 0, 260, 220),filter_cnt.area=41420,filter_cnt.perimeter=2974.31
[1]filter_cnt.br=(134, 2773, 140, 117),filter_cnt.area=7855,filter_cnt.perimeter=771.96
[2]filter_cnt.br=(697, 2704, 318, 186),filter_cnt.area=30024,filter_cnt.perimeter=1873.10
[3]filter_cnt.br=(413, 2266, 120, 122),filter_cnt.area=4515,filter_cnt.perimeter=658.38
[4]filter_cnt.br=(532, 2049, 344, 282),filter_cnt.area=33226,filter_cnt.perimeter=2065.56
[5]filter_cnt.br=(398, 1533, 69, 57),filter_cnt.area=1475,filter_cnt.perimeter=345.50
[6]filter_cnt.br=(0, 0, 638, 933),filter_cnt.area=190862,filter_cnt.perimeter=6977.85
['0,0,1080,2890~0,0,1080,2890']
2023-10-20 17:03:25.178 | WARNING  | __main__:get_grid_masks:6295 - frame_grid_strs=['0,0,1080,2890~0,0,1080,2890']
2023-10-20 17:03:25.179 | WARNING  | __main__:get_grid_masks:6321 - inner_br=(0, 0, 1080, 2890)
2023-10-20 17:03:25.215 | DEBUG    | __main__:wrapper:609 - get_grid_masks took: 0.08秒
2023-10-20 17:03:25.215 | DEBUG    | __main__:get_added_frames:4939 - pic_frame_color='ffffff'
Traceback (most recent call last):
  File "/Users/logic/Downloads/items/MomoTranslator/pyqt5_momotranslator.py", line 4830, in istart_task
    self.step0_analyze_frames()
  File "/Users/logic/Downloads/items/MomoTranslator/pyqt5_momotranslator.py", line 596, in wrapper
    result = func(*args, **kwargs)
  File "/Users/logic/Downloads/items/MomoTranslator/pyqt5_momotranslator.py", line 4683, in step0_analyze_frames
    img_file, frame_grid_strs = analyze1frame(img_file, frame_data, self.auto_subdir, media_type)
  File "/Users/logic/Downloads/items/MomoTranslator/pyqt5_momotranslator.py", line 5156, in analyze1frame
    added_frames = get_added_frames(frame_grid_strs, image_raw, color_name0)
  File "/Users/logic/Downloads/items/MomoTranslator/pyqt5_momotranslator.py", line 4946, in get_added_frames
    'top': get_combined_mask(image_raw[yy + 2:yy + 3, xx:xx + ww],
  File "/Users/logic/Downloads/items/MomoTranslator/pyqt5_momotranslator.py", line 4917, in get_combined_mask
    mask1 = inRange(slice1, lower_bound, upper_bound)
cv2.error: OpenCV(4.6.0) /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/core/src/arithm.cpp:1742: error: (-209:Sizes of input arguments do not match) The lower boundary is neither an array of the same size and same type as src, nor a scalar in function 'inRange'

**Comment by alicewish** [comment]
图片作为附件发上来

**Comment by alicewish** [comment]
另外不同的错误理应开新Issue
