### ISSUE TITLE
No module named cobble

### ISSUE THREAD

**Issue by mobicu** [alicewish/MomoTranslator#28]
`D:\Github\Momo Translator>python pyqt5_momotranslator.py
Traceback (most recent call last):
  File "D:\Github\Momo Translator\pyqt5_momotranslator.py", line 66, in <module>
    from mammoth import convert_to_html
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python310\lib\site-packages\mammoth\__init__.py", line 1, in <module>
    from . import docx, conversion, options, images, transforms, underline
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python310\lib\site-packages\mammoth\docx\__init__.py", line 4, in <module>
    import cobble
ModuleNotFoundError: No module named 'cobble'`

**Comment by alicewish** [comment]
`pip install cobble`
