### ISSUE TITLE
ModuleNotFoundError: No module named 'chardet'

### ISSUE THREAD

**Issue by My12123** [alicewish/MomoTranslator#8]
![2023-04-25_13-24-48](https://user-images.githubusercontent.com/49092250/234249295-cb5c153c-7b60-4d61-92aa-b934a4f9aef0.png)
```python
(venv) F:\MomoTranslator>python pyqt5_momotranslator.py
Traceback (most recent call last):
  File "F:\MomoTranslator\pyqt5_momotranslator.py", line 43, in <module>
    from aip import AipOcr
  File "F:\MomoTranslator\venv\lib\site-packages\aip\__init__.py", line 7, in <module>
    from .nlp import AipNlp
  File "F:\MomoTranslator\venv\lib\site-packages\aip\nlp.py", line 16, in <module>
    import chardet
ModuleNotFoundError: No module named 'chardet'

```

**Comment by alicewish** [comment]
这应该是虚拟环境下pip安装包没装完整造成的。
